# Generated by Django 2.0.7 on 2018-07-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateField()),
                ('text', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'user_messages',
            },
        ),
    ]
