# Generated by Django 2.0.7 on 2018-07-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_album_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(max_length=100)),
            ],
        ),
    ]
